server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: "true"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: "true"

resilience4j:
  circuitbreaker:
    instances:
      subjects:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      subjects:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError